--- #YAML:1.0
name:                Geo-Coordinates-DecimalDegrees
version:             0.08
abstract:            convert between degrees/minutes/seconds and decimal degrees
license:             perl
author:              
    - Walt Mankowski <waltman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Number::Delta:           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
