--- #YAML:1.0
name:                Geo-Coordinates-DecimalDegrees
version:             0.07
abstract:            convert between degrees/minutes/seconds and decimal degrees
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Walt Mankowski <waltman@pobox.com>
